### ISSUE TITLE
No output difference between logic and wire inout port 

### ISSUE THREAD

**Issue by prokie** [DaveMcEwan/svdata#70]
Hi!

First want to say that I really enjoy this script that you guys have written. I use it every day for work. I have also begun learning rust, so I hope that I will be able to contribute in the future.

Here is the issue that I am facing, I am not sure if this is a bug or not. I don't know enough SystemVerilog to understand.

If I run svdata on this module
```
module TestModule (
  inout wire  a,
  inout logic b
);
endmodule
```
I get the following
```
modules:
- identifier: TestModule
  parameters: []
  ports:
  - identifier: a
    direction: Inout
    datakind: Net
    datatype: Logic
    classid: null
    nettype: Wire
    signedness: Unsigned
    packed_dimensions: []
    unpacked_dimensions: []
    comment: null
  - identifier: b
    direction: Inout
    datakind: Net
    datatype: Logic
    classid: null
    nettype: Wire
    signedness: Unsigned
    packed_dimensions: []
    unpacked_dimensions: []
    comment: null
  instances: []
  filepath: test.sv
packages: []
```

I thought it should be different here since port `a` is declared a `wire` and b is `logic`?
